version: '3.7'

services:

  project-name:

    image: project-name:local

    build:
      context: .
      dockerfile: docker/project-name.Dockerfile

    ports:
      - "80:80" 

    deploy:
      replicas: 3 

      resources:
        limits:
          cpus: '0.25'
          memory: 256Mb
        reservations:
          cpus: '0.10'
          memory: 100Mb

